---
# Run with: ansible-playbook -K
- hosts: local
  become: yes
  tasks:
    - name: Install Packages
      dnf:
        state: latest
        update_cache: yes
        name:
          - '@Development Tools'
          - ansible
          - flatpak-builder
          - vim-X11
          - virt-manager
