#!/usr/bin/ansible-playbook -K
---
- hosts: localhost
  tasks:
    - name: Set packages to install
      set_fact:
        dnf_pkgs:
          - '@Development Tools'
          - ansible
          - bash-completion
          - bind-utils
          - glibc-langpack-en # to properly set LANG
          - libxcrypt-compat # for homebrew
          - nmap
          - openssl
          - python3-ansible-lint
          - python3-flake8
          - ruby
          - ShellCheck
          - tmux
          - vim-enhanced # for vimdiff
          - vim-X11
          - youtube-dl

        brew_pkgs:
          - bash-completion
          - fluxcd/tap/flux
          - helm
          - k3sup
          - k9s
          - kubectl
          - kustomize

        dotfiles:
          - source: bash/bash_profile
            dest: ~/.bash_profile

          - source: bash/bashrc
            dest: ~/.bashrc

          - source: git/gitconfig
            dest: ~/.gitconfig

          - source: git/gitignore_global
            dest: ~/.gitignore_global

          - source: mpv
            dest: ~/.config/mpv

          - source: shellcheck/shellcheckrc
            dest: ~/.shellcheckrc

          - source: systemd-tmpfiles
            dest: ~/.config/user-tmpfiles.d

          - source: vim/vimrc
            dest: ~/.vimrc

#------------------------------------------------------------------------------

    - name: Link dotfiles
      file:
        state: link
        force: yes
        src: "{{ playbook_dir }}/files/{{ item.source }}"
        path: "{{ item.dest }}"
      loop: "{{ dotfiles }}"

    - name: Install packages
      become: yes
      register: packages
      dnf:
        state: latest # noqa 403
        name: "{{ dnf_pkgs }}"

    - name: Package report
      block:
        - name: Gather changed packages
          register: package_report
          command: dnf history info
          args:
            warn: no
          # "dnf history info" sometimes throws a python traceback
          failed_when: no

        - name: Show changed packages
          debug:
            var: package_report.stdout_lines
      when: packages is changed

    - name: Install homebrew
      shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        creates: "/home/linuxbrew/.linuxbrew/bin/brew"

    - name: Install homebrew packages
      register: homebrew_packages
      homebrew:
        state: latest # noqa 403
        path: /home/linuxbrew/.linuxbrew/bin
        update_homebrew: yes
        name: "{{ brew_pkgs }}"

    - name: Show changed homebrew packages
      debug:
        var: homebrew_packages.msg
      when: homebrew_packages is changed
