#!/usr/bin/env -S ansible-playbook -K
---
- hosts: local
  become: yes
  tasks:
    - name: Packages
      dnf:
        state: latest
        name:
          - '@Development Tools'
          - ansible
          - flatpak-builder
          - ripgrep
          - vim-enhanced
          - vim-X11
          - virt-manager
          - youtube-dl

    - name: Python modules
      pip:
        state: latest
        name:
          - ansible-lint
          - flake8
