# .bashrc

# Source global definitions
if [[ -f /etc/bashrc ]]; then
    source /etc/bashrc
fi

# For the love of god, no Ctrl+S, Ctrl+Q
stty -ixon -ixoff

# Set the prompt
if [[ -f ~/.bash_prompt ]]; then
    if [[ -n $TOOLBOX_PATH ]]; then
        source ~/.bash_prompt green
    else
        source ~/.bash_prompt
    fi
fi

# User specific aliases and functions
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias mkdir='mkdir -p'
alias ls='ls --color=auto --classify --human-readable --group-directories-first'
alias ll='ls -l'
alias la='ll --almost-all'
alias k='kubectl'

[[ -x $(command -v vimx) ]] && alias vim='vimx'

[[ -z $TOOLBOX_PATH ]] && alias te='toolbox enter'

# Fuzzy finder keyboard shortcuts (line added by install hook)
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
