# .bash_profile

# Source aliases and functions
if [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi

# User specific environment and startup programs
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
export PATH

export HISTCONTROL='ignoreboth'

if [[ -x $(command -v vimx) ]]; then
    export EDITOR='vimx'
else
    export EDITOR='vim'
fi
